apiVersion: v2
name: jupyter
description: Read-only Jupyter Notebook for Greenshift clusters. Connects to MariaDB, MongoDB, and ClickHouse via read-only users. 
type: application
version: 0.1.4
appVersion: "v0.1.1"
keywords:
  - jupyter
  - greenshift
  - analytics
home: https://github.com/greenshift-public-repos/greenshift-jupyter
