apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: notebook
  selector:
    {{- include "jupyter.selectorLabels" . | nindent 4 }}
